spring.application.name=cbnuccc

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=10MB

pepper=${PEPPER}
jwtkey=${JWTKEY}

mailgun.key=${MAILGUN_KEY}
mailgun.domain=${MAILGUN_DOMAIN}

supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}

server.forward-headers-strategy: framework

spring.datasource.url=jdbc:h2:mem:swaggerdb;MODE=PostgreSQL;NON_KEYWORDS=USER;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs